-- most used payment_method
select p.payment_method, COUNT(p.payment_id) as times_used
from payments p
-- WHERE p.payment_status = 'paid'  -> not of much significance
GROUP BY p.payment_method
ORDER BY times_used DESC;

-- most revenue generated by each payment method
SELECT p.payment_method, sum(p.amount) as revenue
from payments p 
WHERE p.payment_status = 'paid'
GROUP BY p.payment_method
ORDER BY revenue DESC;

-- refunded amount by payment method
SELECT p.payment_method, sum(p.amount) as refunded_amount
from payments p 
WHERE p.payment_status = 'refunded'
GROUP BY p.payment_method
ORDER BY refunded_amount DESC;
