-- Products

-- top selling products
select p.product_id,p.product_name, SUM(oi.quantity) as units_sold
from order_items oi 
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_id,p.product_name
ORDER BY units_sold DESC LIMIT 5;

-- top revenue generating products
select p.product_id,p.product_name, SUM(oi.quantity * oi.price_per_unit) as revenue
from order_items oi 
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_id,p.product_name
ORDER BY revenue DESC LIMIT 5;

-- least selling products
select p.product_id,p.product_name, SUM(oi.quantity) as units_sold
from order_items oi 
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_id,p.product_name
ORDER BY units_sold ASC LIMIT 5;

-- least revenue generating products
select p.product_id,p.product_name, SUM(oi.quantity * oi.price_per_unit) as revenue
from order_items oi 
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_id,p.product_name
ORDER BY revenue ASC LIMIT 5;

-- products never purchased
select p.product_id,p.product_name
from products p
left join order_items oi on p.product_id = oi.product_id
WHERE oi.product_id IS NULL;


-- revenue generated by each product
select p.product_id,p.product_name, SUM(oi.quantity * oi.price_per_unit) as revenue
from order_items oi 
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_id,p.product_name;
