
-- revenue generated by each supplier
select s.supplier_id,s.supplier_name, sum(oi.quantity * oi.price_per_unit) as revenue
from order_items oi
JOIN orders o on oi.order_id = o.order_id
join payments pr ON o.order_id = pr.order_id
JOIN products p ON oi.product_id = p.product_id
JOIN suppliers s ON p.supplier_id = s.supplier_id
where pr.payment_status = 'paid'
GROUP BY s.supplier_id,s.supplier_name
ORDER BY revenue DESC;

-- top supplier
select s.supplier_id,s.supplier_name,COUNT(DISTINCT c.category_id) as no_of_supplying_categories,sum(oi.quantity * oi.price_per_unit) as revenue
from order_items oi
JOIN orders o on oi.order_id = o.order_id
join payments pr ON o.order_id = pr.order_id
JOIN products p ON oi.product_id = p.product_id
JOIN suppliers s ON p.supplier_id = s.supplier_id
Join categories c on p.category_id = c.category_id
where pr.payment_status = 'paid'
GROUP BY s.supplier_id,s.supplier_name
ORDER BY revenue DESC;
